image: "node:lts-slim"

stages:
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - .cache

before_script:
  - npm ci --cache .npm --prefer-offline

test:
  stage: test
  script:
    - npm test

pages:
  stage: deploy
  script:
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - master
