name: CI

on:
  push:
    branches:
      - "*"
  pull_request:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('package-lock.json') }}

      - run: npm ci
      - run: npm run build
      - run: npm test

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    needs:
      - build

    permissions:
      pages: write
      id-token: write

    if: github.ref_name == 'master'

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  docker:
    runs-on: ubuntu-latest

    if: github.ref_name == 'master'
    needs:
      - build

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build containers
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/realorangeone/web-rng:latest
